/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROYECTOS;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author grabiel
 */
public class CALCULADORA extends javax.swing.JFrame {

    //VARIANTES 
     private String cadenaNumeros="";
    private String operacion ="";
    private double primerNumero , resultado ;
    private boolean  activado =true ;
    private boolean punto =true;
    
   
    public CALCULADORA() {
        initComponents();
        
         //para que nuestro formulario se ponga en medio
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtoperacion = new javax.swing.JLabel();
        txtresultad = new javax.swing.JLabel();
        btncabiarmodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn8 = new javax.swing.JButton();
        btnpotencia = new javax.swing.JButton();
        btndicicion = new javax.swing.JButton();
        btnmultiplicar = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btneliminarunnumero = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btnmasomenos = new javax.swing.JButton();
        btncero = new javax.swing.JButton();

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        jButton9.setText("C");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 253, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtoperacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtoperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 57, 122, 21));

        txtresultad.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtresultad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtresultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, 298, 60));

        btncabiarmodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BTON_NUEVO_MODO.png"))); // NOI18N
        btncabiarmodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncabiarmodoActionPerformed(evt);
            }
        });
        jPanel1.add(btncabiarmodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(".");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn8.setText("8");
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, 50));

        btnpotencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnpotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btnpotencia.setText("^");
        btnpotencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpotencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnpotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpotenciaActionPerformed(evt);
            }
        });
        jPanel2.add(btnpotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        btndicicion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndicicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btndicicion.setText("/");
        btndicicion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndicicion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btndicicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndicicionActionPerformed(evt);
            }
        });
        jPanel2.add(btndicicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 50, 50));

        btnmultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnmultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btnmultiplicar.setText("*");
        btnmultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmultiplicar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicarActionPerformed(evt);
            }
        });
        jPanel2.add(btnmultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 50, 50));

        btnresta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnresta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btnresta.setText("-");
        btnresta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnresta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });
        jPanel2.add(btnresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 50, 50));

        btnsuma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnsuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btnsuma.setText("+");
        btnsuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsuma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });
        jPanel2.add(btnsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 50, 50));

        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btnlimpiar.setText("C");
        btnlimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnlimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 50));

        btneliminarunnumero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btneliminarunnumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonn1.png"))); // NOI18N
        btneliminarunnumero.setText("CE");
        btneliminarunnumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminarunnumero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btneliminarunnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarunnumeroActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminarunnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 50));

        btnigual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnigual.setForeground(new java.awt.Color(255, 255, 255));
        btnigual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnigual.png"))); // NOI18N
        btnigual.setText("=");
        btnigual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnigual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        jPanel2.add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 50, 50));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn9.setText("9");
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 50));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn7.setText("7");
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 50));

        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        jButton12.setText("C");
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, 50));

        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        jButton14.setText("C");
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 50));

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        jButton15.setText("C");
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 50));

        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        jButton16.setText("C");
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, 50));

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        jButton17.setText("C");
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 50));

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        jButton18.setText("C");
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 50));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn5.setText("5");
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 50, 50));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn6.setText("6");
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 50, 50));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn4.setText("4");
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 50));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn2.setText("2");
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 50, 50));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn3.setText("3");
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 50, 50));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btn1.setText("1");
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 50));

        btnpunto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnpunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btnpunto.setText(".");
        btnpunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpunto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        jPanel2.add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 50, 50));

        btnmasomenos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnmasomenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btnmasomenos.setText("+/-");
        btnmasomenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmasomenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btnmasomenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasomenosActionPerformed(evt);
            }
        });
        jPanel2.add(btnmasomenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 50, 50));

        btncero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btncero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnn2.png"))); // NOI18N
        btncero.setText("0");
        btncero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_n1_clik.png"))); // NOI18N
        btncero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceroActionPerformed(evt);
            }
        });
        jPanel2.add(btncero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 330, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
            this.txtoperacion.setText("");
        this.txtresultad.setText("0");
        cadenaNumeros="";
        operacion="nula";
        activado=true;
        punto =true;
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="7";
    
}else{
    cadenaNumeros+="7";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    
    
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="8";
    
}else{
    cadenaNumeros+="8";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="9";
    
}else{
    cadenaNumeros+="9";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="4";
    
}else{
    cadenaNumeros+="4";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="5";
    
}else{
    cadenaNumeros+="5";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="6";
    
}else{
    cadenaNumeros+="6";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="1";
    
}else{
    cadenaNumeros+="1";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="2";
    
}else{
    cadenaNumeros+="2";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="3";
    
}else{
    cadenaNumeros+="3";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceroActionPerformed
        // TODO add your handling code here:
           if (this.txtresultad.getText().equals("0")){
    cadenaNumeros="0";
    
}else{
    cadenaNumeros+="0";

}

    this.txtresultad.setText(cadenaNumeros);
    activado=true;//boi a usar la calculadora
    }//GEN-LAST:event_btnceroActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        // TODO add your handling code here:
        if (punto== true){
        
      if (cadenaNumeros.equals("")){
       cadenaNumeros = "0.";
       
    }else{
          cadenaNumeros +=".";
    }
      this.txtresultad.setText(cadenaNumeros);
      punto= false;
    
    }
    }//GEN-LAST:event_btnpuntoActionPerformed

    private void btnpotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpotenciaActionPerformed
        // TODO add your handling code here:
         primerNumero = Double.parseDouble(cadenaNumeros);
    this.txtoperacion.setText("sqrt("+cadenaNumeros+")");
    resultado = Math.sqrt(primerNumero);
    this.txtresultad.setText(String.format("%.2f", resultado));
    cadenaNumeros= String.valueOf(resultado);
    }//GEN-LAST:event_btnpotenciaActionPerformed

    private void btndicicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndicicionActionPerformed
        // TODO add your handling code here:
               if (activado == true ){
    primerNumero = Double.parseDouble(cadenaNumeros);
    this.txtoperacion.setText(cadenaNumeros + "/");
    cadenaNumeros="";
    operacion = "dividir";
    
    activado = false;
               }
    }//GEN-LAST:event_btndicicionActionPerformed

    private void btnmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicarActionPerformed
        // TODO add your handling code here:
        if (activado == true ){
    primerNumero = Double.parseDouble(cadenaNumeros);
    this.txtoperacion.setText(cadenaNumeros + "*");
    cadenaNumeros="";
    operacion = "multiplicar";
    
    activado = false;
    
}
    }//GEN-LAST:event_btnmultiplicarActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        // TODO add your handling code here:
        if (activado == true ){
    primerNumero = Double.parseDouble(cadenaNumeros);
    this.txtoperacion.setText(cadenaNumeros + "-");
    cadenaNumeros="";
    operacion = "restar";
    
    activado = false;
    
}
    }//GEN-LAST:event_btnrestaActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        // TODO add your handling code here:
        if (activado == true ){
    primerNumero = Double.parseDouble(cadenaNumeros);
    this.txtoperacion.setText(cadenaNumeros + "+");
    cadenaNumeros="";
    operacion = "sumar";
    
    activado = false;
    
}
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        // TODO add your handling code here:
        double segundoNumero;

if (operacion.equals("nula")){
    this.txtresultad.setText(cadenaNumeros);
}else if (operacion.equals("sumar")){
    segundoNumero = Double.parseDouble(cadenaNumeros);
    resultado = primerNumero + segundoNumero;;
    this.txtresultad.setText(String.format("% .2f", resultado));
    cadenaNumeros = String.valueOf(resultado);
    operacion = "nula";
     
}else if (operacion.equals("restar")){
    segundoNumero = Double.parseDouble(cadenaNumeros);
    resultado = primerNumero - segundoNumero;;
    this.txtresultad.setText(String.format("% .2f", resultado));
    cadenaNumeros = String.valueOf(resultado);
    operacion = "nula";
    
}else if (operacion.equals("multiplicar")){
    segundoNumero = Double.parseDouble(cadenaNumeros);
    resultado = primerNumero * segundoNumero;;
    this.txtresultad.setText(String.format("% .2f", resultado));
    cadenaNumeros = String.valueOf(resultado);
    operacion = "nula";
    
}else if (operacion.equals("dividir")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            if (segundoNumero == 0) {
                this.txtresultad.setText("NoseDividePor0");
            } else {
                resultado = primerNumero / segundoNumero;;
                this.txtresultad.setText(String.format("% .2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            }

        }

this.txtoperacion.setText("");
activado =true;
punto =false;

        
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnmasomenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasomenosActionPerformed
        // TODO add your handling code here:
        if (cadenaNumeros.charAt(0)!='-'){
        cadenaNumeros = "-"+cadenaNumeros;
    }else{
        cadenaNumeros=cadenaNumeros.substring(1,cadenaNumeros.length());
    }
this.txtresultad.setText(cadenaNumeros);
    }//GEN-LAST:event_btnmasomenosActionPerformed

    private void btneliminarunnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarunnumeroActionPerformed
        // TODO add your handling code here:
        int tamaño = cadenaNumeros.length();
if (tamaño > 0){
    if(tamaño==1){
    cadenaNumeros="0";
    
}else{
    cadenaNumeros=cadenaNumeros.substring(0,cadenaNumeros.length()-1);
}
    this.txtresultad.setText(cadenaNumeros);
}
        
    }//GEN-LAST:event_btneliminarunnumeroActionPerformed
//bariante paraq cambiar le modo oscuro
    boolean modoOscuro=false;

    private void btncabiarmodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncabiarmodoActionPerformed
        // TODO add your handling code here:
        if (!modoOscuro){
            
         jPanel1.setBackground(Color.decode("#212b41"));
                jPanel2.setBackground(Color.decode("#2e3951"));
                this.txtoperacion.setForeground(Color.decode("#0db387"));
                this.txtresultad.setForeground(Color.decode("#0db387"));

         cambiarColorBtn2(btn1);
          cambiarColorBtn2(btn2);
           cambiarColorBtn2(btn3);
            cambiarColorBtn2(btn4);
             cambiarColorBtn2(btn5);
              cambiarColorBtn2(btn6);
               cambiarColorBtn2(btn7);
                cambiarColorBtn2(btn8);
                 cambiarColorBtn2(btn9);
                  cambiarColorBtn2(btncero);
                   cambiarColorBtn2(btnpunto);
                   cambiarColorBtn2(btnmasomenos);
                   
                      cambiarColorBtn1(btnlimpiar);
                        cambiarColorBtn1(btneliminarunnumero);
                          cambiarColorBtn1(btnpotencia); 
                          cambiarColorBtn1(btndicicion);
                            cambiarColorBtn1(btnmultiplicar);
                              cambiarColorBtn1(btnresta);
                                cambiarColorBtn1(btnsuma);
                          
                                  
          btnigual.setIcon(new ImageIcon(getClass().getResource("/images/bton_negroi_igual.png")));
          btnigual.setPressedIcon(new ImageIcon(getClass().getResource("/images/bton_negroi_igual.png")));
          btnigual.setRolloverIcon(new ImageIcon(getClass().getResource("/images/BTON_PRESIONAR_NEGRO.png")));
          btnigual.setForeground(Color.decode("#96a8a0"));
          //PARA E4L BOTON
          btncabiarmodo.setIcon(new ImageIcon(getClass().getResource("/images/BOTON_CAMNBIAR_CLARO.png")));
          modoOscuro=true;
        }else{
            CALCULADORA cambiar= new CALCULADORA();
            this.dispose();
            cambiar.setVisible(true);
            
        }
                          
                   
          
    }//GEN-LAST:event_btncabiarmodoActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    public void cambiarColorBtn2(JButton btn){
          btn.setIcon(new ImageIcon(getClass().getResource("/images/BTON_NEGRO_01.png")));
          btn.setPressedIcon(new ImageIcon(getClass().getResource("/images/BTON_NEGRO_01.png")));
          btn.setRolloverIcon(new ImageIcon(getClass().getResource("/images/BTON_PRESIONAR_NEGRO.png")));
          btn.setForeground(Color.decode("#96a8a0"));
          
    }
     
      public void cambiarColorBtn1(JButton btn){
          btn.setIcon(new ImageIcon(getClass().getResource("/images/BOTON_NEGRO_02.png")));
          btn.setPressedIcon(new ImageIcon(getClass().getResource("/images/BOTON_NEGRO_02.png")));
          btn.setRolloverIcon(new ImageIcon(getClass().getResource("/images/BTON_PRESIONAR_NEGRO.png")));
          btn.setForeground(Color.decode("#18d4a3"));
          
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULADORA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btncabiarmodo;
    private javax.swing.JButton btncero;
    private javax.swing.JButton btndicicion;
    private javax.swing.JButton btneliminarunnumero;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmasomenos;
    private javax.swing.JButton btnmultiplicar;
    private javax.swing.JButton btnpotencia;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtoperacion;
    private javax.swing.JLabel txtresultad;
    // End of variables declaration//GEN-END:variables
}
