/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm_tienda;


import CONTROL.proceso;
import PROYECTO_LOYIN.login;
import clases_frm.claseUsuario;
import clases_frm.datos_tienda;
import clases_frm.usuarioGenaral;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Frame;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author grabiel
 */
public class frmcarrito extends javax.swing.JFrame {

      claseUsuario resibir =usuarioGenaral.transferencia;
      String  saldito ="";
      double sum=0;
      
      //para audios
      AudioClip sonido2;
       AudioClip sonido4;
           AudioClip sonido5;
           
           
    public frmcarrito() {
        initComponents();
        
        //audios
          sonido2=java.applet.Applet.newAudioClip(getClass().getResource("/audios/audiodespedida.wav"));
               sonido4=java.applet.Applet.newAudioClip(getClass().getResource("/audios/sonidoBotoon03.wav"));
                    sonido5=java.applet.Applet.newAudioClip(getClass().getResource("/audios/audiocompraaexito.wav"));
                    
                    
                    
                    
                    
                    //centar
        this.setLocationRelativeTo(null);
        
        //llenar mi tabla
          llenarTabla();  
    
    //pata ver mi saldo
          saldoVer();
     
claseUsuario resibir =usuarioGenaral.transferencia;
      this.txtusuario.setText(""+resibir.getUsuario());
      
//      this.txtsaldo.setText(saldito);

    if ( proceso.modooscuro ) {
     
      this.fondo02.setIcon(new ImageIcon(getClass().getResource("/imagenes_Tienda/fondo-mediun-noiche-negro-033.png")));
       this.fondo01.setIcon(new ImageIcon(getClass().getResource("/imagenes_Tienda/fondo-linia-noche-03.png")));
       jLabel8.setIcon(new ImageIcon(getClass().getResource("/imagenes_Tienda/fondo-paramitabla-megro.png")));
       
       jLabel3.setForeground(Color.white);
        jLabel5.setForeground(Color.white);
        
        
        this.jPanel2.setBackground(Color.BLACK);
            this.jPanel1.setBackground(Color.BLACK);
                this.jPanel3.setBackground(Color.BLACK);
        
         jLabel1.setForeground(Color.white);
          txt_totalApagar.setForeground(Color.white);
          txt_totalApagar.setBackground(Color.black);
         jSeparator1.setForeground(Color.white);
         
    }

}
    
  public void saldoVer(){
         try{
           // Definir el archivo de texto
        File archivo = new File("BD_USUARIOS.txt");
        Scanner lector = new Scanner(archivo);
        
          java.util.List<String> lineas = new java.util.ArrayList<String>();
        while (lector.hasNextLine()) {
          lineas.add(lector.nextLine());
        }
        lector.close();
        
        
        
         for (int i = 0; i < lineas.size(); i++) {
          String[] partes = lineas.get(i).split("-");
          String usuario= partes[0];
          String saldo=partes[5];
          
          
             if (usuario.equals(resibir.getUsuario())) {
                    this.txtsaldo.setText(saldo);
          saldito=saldo;
         
//          JOptionPane.showMessageDialog(null, "Correo Electronico encontrado");
            return;
          }
         }
         
//            JOptionPane.showMessageDialog(null, "correo Herroneo");
              
               
        
        }catch(IOException ex){
             JOptionPane.showMessageDialog(null, "Error al leer o escribir en el archivo");
            ex.printStackTrace();
        }
        
                
                
    
  }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltotal = new javax.swing.JTable();
        txt_totalApagar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btncomprar = new javax.swing.JButton();
        btneliminarProducto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnrecargar = new javax.swing.JButton();
        btncerrarseccion = new javax.swing.JButton();
        lblminimizar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblsalir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        fondo01 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbltotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CATEGORIA", "PRODUCTO", "PRECIO", "CANTIDAD", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbltotal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 720, 240));

        txt_totalApagar.setEditable(false);
        txt_totalApagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_totalApagar.setBorder(null);
        txt_totalApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalApagarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_totalApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total A Pagar :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, 30));

        btncomprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/bottonComprar.png"))); // NOI18N
        btncomprar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/bottoncomprar_presionado.png"))); // NOI18N
        btncomprar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/bottoncomprar_presionado.png"))); // NOI18N
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });
        jPanel2.add(btncomprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 100, 30));

        btneliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_productoeliminar.png"))); // NOI18N
        btneliminarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_productoeliminado_presionado.png"))); // NOI18N
        btneliminarProducto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_productoeliminado_presionado.png"))); // NOI18N
        btneliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 130, 20));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 390));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 860, 390));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/logoGrande_market.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 260, 70));

        btnrecargar.setBackground(new java.awt.Color(0, 0, 0));
        btnrecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/Recargar_btn.png"))); // NOI18N
        btnrecargar.setBorder(null);
        btnrecargar.setBorderPainted(false);
        btnrecargar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/recargar_presionado.png"))); // NOI18N
        btnrecargar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/recargar_presionado.png"))); // NOI18N
        btnrecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecargarActionPerformed(evt);
            }
        });
        jPanel3.add(btnrecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 70, 70));

        btncerrarseccion.setBackground(new java.awt.Color(0, 0, 0));
        btncerrarseccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/cerrar_seccion_new.png"))); // NOI18N
        btncerrarseccion.setBorder(null);
        btncerrarseccion.setBorderPainted(false);
        btncerrarseccion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/cerra_seccion_new_presionado.png"))); // NOI18N
        btncerrarseccion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/cerra_seccion_new_presionado.png"))); // NOI18N
        btncerrarseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarseccionActionPerformed(evt);
            }
        });
        jPanel3.add(btncerrarseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 70, -1));

        lblminimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/redondito_fondonegro_minimizar.png"))); // NOI18N
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });
        jPanel3.add(lblminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/redondito_fondonegro_cuadrado.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        lblsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_productos/rdondito_fondo_negro_salir.png"))); // NOI18N
        lblsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalirMouseClicked(evt);
            }
        });
        jPanel3.add(lblsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Saldo :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        txtsaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsaldo.setEnabled(false);
        jPanel3.add(txtsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 160, -1));

        txtusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtusuario.setEnabled(false);
        jPanel3.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 180, -1));
        jPanel3.add(fondo01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1170, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1180, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Inicio ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("/ Carrito");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 30));
        jPanel1.add(fondo02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1170, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

          private void llenarTabla(){
//                String cabezera[]={"ID","TIPO","PRODUCTO","PRESIO","CANTIDAD","SUB TOTAL"};
  DefaultTableModel modeloDefault = new DefaultTableModel(new String[]{"ID","CATEGORIA","PRODUCTO","PRESIO","CANTIDAD","SUB TOTAL"},clase_gloval.inicio.size());
        //colocamos las cabezeras
        //con eso dfinimos las cabezeras de las tablas ycuntas filas va a qeuerer
//        DefaultTableModel modeloDefault = new DefaultTableModel(new String[]{"ID","PRODUCTO","PRESIO","CANTIDAD"},CLASE_REGISTRO_GLOVAL.inicio.size());
   this.tbltotal.setModel(modeloDefault);
   
   //ingresamos toda lainformacion a nuetsra lista 
TableModel modeloDatos = this.tbltotal.getModel();
//el for para resetear en que fila vamos a poner nuestro elemento
 
double tot=0;
for (int i=0;i<clase_gloval.inicio.size();i++){
       datos_tienda persona= clase_gloval.inicio.get(i);
    //cocollamos los datos en que posicion iraa
 
      modeloDatos.setValueAt(persona.getId(),i , 0);
      modeloDatos.setValueAt(persona.getTipo_producto(),i , 1);
      modeloDatos.setValueAt(persona.getProducto(),i , 2);
      modeloDatos.setValueAt(persona.getPresio(),i , 3);
      modeloDatos.setValueAt(persona.getCantidad(),i , 4);
      modeloDatos.setValueAt(persona.getSubTotal(),i , 5);
        

  
            tot=tot+persona.getSubTotal();
            
}
 sum=tot;
 this.txt_totalApagar.setText(String.valueOf(tot));

    }
          

    
    private void btneliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarProductoActionPerformed
        // TODO add your handling code here:
        //para elkiminar un producto
        
        //llamamos a nuestra tabla
          sonido4.play();
             int eliminarFila = this.tbltotal.getSelectedRow();
        
        if (eliminarFila>=0 ){
            //asemos el llamado anuestro arayList y el remove se encarga de elimnia dicha fila
            clase_gloval.inicio.remove(eliminarFila);
            llenarTabla();
        }
    }//GEN-LAST:event_btneliminarProductoActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        // TODO add your handling code here:
   DefaultTableModel modelo = (DefaultTableModel) this.tbltotal.getModel();
DecimalFormat formato = new DecimalFormat("#.##");
       double diferencia;
       if (sum> Double.parseDouble(saldito)){
           JOptionPane.showMessageDialog(rootPane,"saldo Insuficiente");
       }else{
     String direccion = JOptionPane.showInputDialog(null, "Ingresar su Dirección:", "Datos de Envio", JOptionPane.PLAIN_MESSAGE);
//    System.out.println("La dirección ingresada es: " + direccion);
    
              diferencia =  Double.parseDouble(saldito)-sum;
           
       
       
       
         try {
        // Definir el archivo de texto
        File archivo = new File("BD_USUARIOS.txt");
        Scanner lector = new Scanner(archivo);

        // Leer el archivo y almacenar cada línea en una lista
        java.util.List<String> lineas = new java.util.ArrayList<String>();
        while (lector.hasNextLine()) {
          lineas.add(lector.nextLine());
        }
        lector.close();

        // Recorrer las líneas y buscar el correo que deseas modificar
        for (int i = 0; i < lineas.size(); i++) {
          String[] partes = lineas.get(i).split("-");
          String usuario = partes[0];
          String saldo = partes[5];
          if (usuario.equals(resibir.getUsuario())) {
            // Modificar la contraseña en esta línea
            
            partes[5] =""+formato.format(diferencia);

            // Actualizar la línea en la lista
            lineas.set(i, String.join("-", partes));

            // Escribir la lista actualizada de vuelta en el archivo de texto
            FileWriter escritor = new FileWriter(archivo);
            for (String linea : lineas) {
              escritor.write(linea + "\n");
            }
            escritor.close();
       sonido5.play();
            JOptionPane.showMessageDialog(null, "Compra exitosa !! Grasias por comprar en Smart Marquet ");
           clase_gloval.inicio.clear();
      modelo.setRowCount(0);
      this.txt_totalApagar.setText("");
     
            return;
          }
        }

        JOptionPane.showMessageDialog(null, "Usuario herroneo");

      } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error al leer o escribir en el archivo");
        ex.printStackTrace();
      }
       }
      
    }//GEN-LAST:event_btncomprarActionPerformed

    private void btnrecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecargarActionPerformed
        // TODO add your handling code here:
        sonido4.play();
              frmrecargar abrir = new frmrecargar();
        abrir.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnrecargarActionPerformed

    private void btncerrarseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarseccionActionPerformed
        // TODO add your handling code here:
        sonido2.play();
        login abrir = new login ();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncerrarseccionActionPerformed

    private void lblsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalirMouseClicked
        // TODO add your handling code here:
        portada abrir = new portada();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblsalirMouseClicked

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        // TODO add your handling code here:
         this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void txt_totalApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalApagarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
            portada abrir = new portada();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked


   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmcarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmcarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmcarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmcarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmcarrito().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrarseccion;
    private javax.swing.JButton btncomprar;
    private javax.swing.JButton btneliminarProducto;
    private javax.swing.JButton btnrecargar;
    private javax.swing.JLabel fondo01;
    private javax.swing.JLabel fondo02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JLabel lblsalir;
    private javax.swing.JTable tbltotal;
    private javax.swing.JTextField txt_totalApagar;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
