/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROYECTO_LOYIN;

import CONTROL.proceso;
import REGISTRO.empleado;
import java.applet.AudioClip;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.BufferedReader;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;




public class ADMINISTRADOR extends javax.swing.JFrame {

    //llamo ami clase
proceso objp = new proceso();
//asemos las cabeceras anuesrtra tabla
String [] cabecera={"Nombre","Apellido","Correo","Telefono","Contraseña","saldo"};
DefaultTableModel modelo = new DefaultTableModel(null,cabecera);

DefaultListModel h = new DefaultListModel();

AudioClip sonido2;

    public ADMINISTRADOR() {
        initComponents();
        this.tblmostrar.setModel(modelo);
        
        this.setLocationRelativeTo(null);
       
        sonido2=java.applet.Applet.newAudioClip(getClass().getResource("/audios/sonido_clik.wav"));
        
        
         if (  proceso.modooscuro ) {
              //para el fondo 01 negro
          this.lblsalir.setIcon(new ImageIcon(getClass().getResource("/imagen_login/fondo-admin.jpg")));
           this.jLabel1.setIcon(new ImageIcon(getClass().getResource("/imagen_registro/logoMediano_market.png")));
          
         }
        
        
        
    }
    
    private void listar(){
        try{
        
            //vamos a limpiar nuestra tabla
            modelo.setRowCount(0);//lipiar tabla
            //vamos aleer
            objp.leer();
            for (empleado e:objp.array){
                
                Object [] fila ={e.getNombre(),e.getApe(),e.getCorreo(),e.getTelefono(),e.getContra(),e.getSaldo()};
                //mandamos la informacion a nuestra tabla
                modelo.addRow(fila);
               
             
               
            
            }
           
        
        
        }catch(Exception e){
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTNusuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmostrar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblcuadrado = new javax.swing.JLabel();
        lblmini = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblsalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_mosrtrardatos.png"))); // NOI18N
        BTNusuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_presionarMostradatos.png"))); // NOI18N
        BTNusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNusuariosActionPerformed(evt);
            }
        });
        jPanel1.add(BTNusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 90, 30));

        tblmostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblmostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblmostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 561, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/logo_market_02.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_login/redondondito_rojo_noche.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        lblcuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_login/redondito_amarilo_nocche.png"))); // NOI18N
        lblcuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcuadradoMouseClicked(evt);
            }
        });
        jPanel1.add(lblcuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        lblmini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_login/redondito_verde_noche.jpg"))); // NOI18N
        lblmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminiMouseClicked(evt);
            }
        });
        jPanel1.add(lblmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 30, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_regresar.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_presionarRegresar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 90, 30));

        lblsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/fondoProvando (2).jpg"))); // NOI18N
        jPanel1.add(lblsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNusuariosActionPerformed
        //vamos aleer
        sonido2.play();
        listar();
        
        
    }//GEN-LAST:event_BTNusuariosActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        sonido2.play();
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminiMouseClicked
        // TODO add your handling code here:
        sonido2.play();
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblminiMouseClicked

    private void lblcuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcuadradoMouseClicked
        // TODO add your handling code here:
        sonido2.play();
           boolean agrandado = false;
            if (agrandado) {
                    setSize(new Dimension(960, 710));
                  
                    agrandado = false;
                } else {
                    setSize(new Dimension(1200, 1010));
                    this.setLocationRelativeTo(this);
                  
                    agrandado = true;
                }
       
    }//GEN-LAST:event_lblcuadradoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           sonido2.play();
        login abrir = new login();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMINISTRADOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNusuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcuadrado;
    private javax.swing.JLabel lblmini;
    private javax.swing.JLabel lblsalir;
    private javax.swing.JTable tblmostrar;
    // End of variables declaration//GEN-END:variables
}
