/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROYECTO_LOYIN;

import CONTROL.proceso;
import java.applet.AudioClip;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author grabiel
 */
public class frm_olvidastes_contra extends javax.swing.JFrame {

    AudioClip audio2;
    /**
     * Creates new form frm_olvidastes_contra
     */
    public frm_olvidastes_contra() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        audio2=java.applet.Applet.newAudioClip(getClass().getResource("/audios/sonido_clik.wav"));
        
          if ( proceso.modooscuro ) {
          this.jLabel4.setIcon(new ImageIcon(getClass().getResource("/imagen_registro/FONFOolvidastecontraseña-darck.jpg")));
   
           this.jLabel1.setForeground(Color.WHITE);
           this.jLabel2.setForeground(Color.WHITE);
           this.jLabel3.setForeground(Color.WHITE);
           this.rbtcorreo.setForeground(Color.WHITE);
           this.rbttelefono.setForeground(Color.WHITE);
             this.rbtcorreo.setBackground(Color.black);
           this.rbttelefono.setBackground(Color.black);
           this.btnsolicitar.setBackground(Color.black);
             this.btnsolicitar.setForeground(Color.black);
           
            this.jPanel2.setBackground(Color.black);
            
            Border bordeNegro = BorderFactory.createLineBorder(Color.BLACK);
            this.jPanel2.setBorder(bordeNegro);
           
              this.jLabel5.setIcon(new ImageIcon(getClass().getResource("/imagen_registro/iconCorreo-blanco.jpg")));
              this.jLabel6.setIcon(new ImageIcon(getClass().getResource("/imagen_registro/iconotelefonoBlanco.jpg")));
         this.jLabel7.setIcon(new ImageIcon(getClass().getResource("/imagen_registro/logoMediano_market.png")));
            
      
        }
        
        
    }

    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobutton_recuperarcontra = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbtcorreo = new javax.swing.JRadioButton();
        rbttelefono = new javax.swing.JRadioButton();
        btnsolicitar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel1.setText("!Ops!  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("olvidates tu contraseña /usuario :(");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("¿como te gustaria recuperarla?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        rbtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        grupobutton_recuperarcontra.add(rbtcorreo);
        rbtcorreo.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        rbtcorreo.setText("correo electronico ");
        jPanel2.add(rbtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        rbttelefono.setBackground(new java.awt.Color(255, 255, 255));
        grupobutton_recuperarcontra.add(rbttelefono);
        rbttelefono.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        rbttelefono.setText("numero telefonico");
        rbttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(rbttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnsolicitar.setForeground(new java.awt.Color(255, 255, 255));
        btnsolicitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/bottonsolicitar.png"))); // NOI18N
        btnsolicitar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/botton_presionarsolicitar.png"))); // NOI18N
        btnsolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsolicitarActionPerformed(evt);
            }
        });
        jPanel2.add(btnsolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/iconologinnew (1).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/icontelefonoo (1).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 230, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/logo_market_02.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 220, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_registro/fondoProvando (2).jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsolicitarActionPerformed
        // TODO add your handling code here:
        audio2.play();
        if(this.rbtcorreo.isSelected()){
            frmcorreoR abrir = new frmcorreoR();
            abrir.setVisible(true);
            this.dispose();
        }
        if (this.rbttelefono.isSelected()){
             frmTelefonoR abrir = new frmTelefonoR();
            abrir.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnsolicitarActionPerformed

    private void rbttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttelefonoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbttelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_olvidastes_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_olvidastes_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_olvidastes_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_olvidastes_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_olvidastes_contra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsolicitar;
    private javax.swing.ButtonGroup grupobutton_recuperarcontra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtcorreo;
    private javax.swing.JRadioButton rbttelefono;
    // End of variables declaration//GEN-END:variables
}
